name: Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Coverlet
      uses: b3b00/coverlet-action@1.1.7
      with:
        testProject: 'ParserTest/ParserTest.csproj'
        output: 'coverage.opencover.xml'
        outputFormat: 'opencover'
        excludes: '[test]test.*'
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
