name: Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Coverlet
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
